# This file generates the GitHub Actions matrix.

board:
  - nice_nano

shield:
  - charybdis_dongle
  - settings_reset

format:
  - dongle
  - reset

include:
  - board: nice_nano
    shield: charybdis_dongle
    keymap: qwerty
    snippet: studio-rpc-usb-uart
